#pragma once

struct ThreadData {
	ULONG ThreadId;
	int Priority;
};

#define PRIORITY_OVERRIDER_DEVICE 0x8000

#define IOCTL_PRIORITY_OVERRIDER_SET_PRIORITY CTL_CODE(PRIORITY_OVERRIDER_DEVICE, \
0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
